spring:
  application:
    name: provider-order                            # 微服务名称
  jpa:                                                         # Jpa配置
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    # Druid数据源连接池配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    #注意要配置serverTimezone等信息
    url: jdbc:mysql://mysql:3306/lycloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,Slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=32
  zipkin:
    base-url: http://zipkin:9411
    sleuth:
      sampler:
        rate: 1
seata:
  tx-service-group: lycloud_tx_group
  service:
    vgroup-mapping:
      lycloud_tx_group: default
    grouplist:
      default: 172.18.8.51:8091